name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      # 修复1: 确保使用兼容的 Bundler 版本
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-version: '2.3.26'  # 明确指定兼容版本
          bundler-cache: false       # 禁用自动缓存，手动处理
          cache-version: 2           # 更新缓存版本强制刷新
          
      # 修复2: 解决平台参数问题
      - name: Install Dependencies with Platform Fix
        run: |
          # 解决平台问题的替代方案
          bundle config set --local force_ruby_platform true
          
          # 安装依赖，使用--force参数覆盖潜在问题
          bundle install --jobs 4 --retry 3 --force
          
          # 验证安装
          bundle info
          
      # 修复3: 配置缓存路径（Bundler 2.x兼容方式）
      - name: Configure Bundle Path
        run: |
          # 替代 --path 参数的设置方式
          bundle config --local path vendor/bundle
          echo "BUNDLE_PATH set to: vendor/bundle"
          
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
        
      # 添加环境验证
      - name: Verify Environment
        run: |
          echo "Ruby version: $(ruby -v)"
          echo "Bundler version: $(bundle -v)"
          bundle list
          bundle config list

      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}" --trace
        env:
          JEKYLL_ENV: production
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
